image: maven:3-jdk-8

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  GIT_STRATEGY: fetch
  ## GIT_SUBMODULE_STRATEGY: recursive
  ## GIT_DEPTH: "3"

before_script:
  - 'which ssh-agent || ( yum update -y && yum install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$PRODUCT_INFO_CI_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
##  - ssh-keyscan localhost >> ~/.ssh/known_hosts
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git submodule sync --recursive
  - git submodule update --init --recursive --force --remote
  - node -v
  - npm -v

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - test
  - build_jar
  - build_docker

test:
  stage: test
  script:
  - mvn test


build_jar:
  stage: build_jar
  script:
      - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
        - target/productinfo-0.0.1-SNAPSHOT.jar
  only:
    - dev
    - master


build_docker:
  image: docker:latest
  services:
      - docker:dind
  stage: build_docker
  script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 10.1.99.23
      - docker build -t 10.1.99.23/development/product-info .
      - docker push 10.1.99.23/development/product-info
  only:
      - master
