package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;

/**
 * AvailableBinSection generated by hbm2java
 */
@Entity
@Table(name = "available_bin_section", schema = "bpi" )
public class AvailableBinSection implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private AvailableBin availableBin;
	private Integer availableSection;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public AvailableBinSection() {
	}

	public AvailableBinSection(Integer id, AvailableBin availableBin, Integer availableSection, Boolean isDeleted,
			String createdBy, Date createdDate) {
		this.id = id;
		this.availableBin = availableBin;
		this.availableSection = availableSection;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public AvailableBinSection(Integer id, AvailableBin availableBin, Integer availableSection, Boolean isDeleted,
			String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
		this.id = id;
		this.availableBin = availableBin;
		this.availableSection = availableSection;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "available_bin_id", nullable = false)
	public AvailableBin getAvailableBin() {
		return this.availableBin;
	}

	public void setAvailableBin(AvailableBin availableBin) {
		this.availableBin = availableBin;
	}

	@Column(name = "available_section", nullable = false)
	public Integer getAvailableSection() {
		return this.availableSection;
	}

	public void setAvailableSection(Integer availableSection) {
		this.availableSection = availableSection;
	}

	@Column(name = "is_deleted", nullable = false)
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
