package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AvailableBin generated by hbm2java
 */
@Entity
@Table(name = "available_bin", schema = "bpi" )
public class AvailableBin implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private MsPlant msPlant;
	private MsStorageLocation msStorageLocation;
	private String storageType;
	private String storageBin;
	private String storageBinType;
	private Boolean isEmpty;
	private BigDecimal remainingCapacity;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private String emptyBinIndicator;
	private String warehouseNumber;
	private Set<AvailableBinSection> availableBinSections = new HashSet<AvailableBinSection>(0);

	public AvailableBin() {
	}

	public AvailableBin(Integer id, MsPlant msPlant, String storageType, String storageBin, String storageBinType,
			Boolean isEmpty, Boolean isDeleted, String createdBy, Date createdDate) {
		this.id = id;
		this.msPlant = msPlant;
		this.storageType = storageType;
		this.storageBin = storageBin;
		this.storageBinType = storageBinType;
		this.isEmpty = isEmpty;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public AvailableBin(Integer id, MsPlant msPlant, MsStorageLocation msStorageLocation, String storageType,
			String storageBin, String storageBinType, Boolean isEmpty, BigDecimal remainingCapacity, Boolean isDeleted,
			String createdBy, Date createdDate, String updatedBy, Date updatedDate, String emptyBinIndicator,
			String warehouseNumber, Set<AvailableBinSection> availableBinSections) {
		this.id = id;
		this.msPlant = msPlant;
		this.msStorageLocation = msStorageLocation;
		this.storageType = storageType;
		this.storageBin = storageBin;
		this.storageBinType = storageBinType;
		this.isEmpty = isEmpty;
		this.remainingCapacity = remainingCapacity;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.emptyBinIndicator = emptyBinIndicator;
		this.warehouseNumber = warehouseNumber;
		this.availableBinSections = availableBinSections;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plant_id", nullable = false)
	public MsPlant getMsPlant() {
		return this.msPlant;
	}

	public void setMsPlant(MsPlant msPlant) {
		this.msPlant = msPlant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_location_id")
	public MsStorageLocation getMsStorageLocation() {
		return this.msStorageLocation;
	}

	public void setMsStorageLocation(MsStorageLocation msStorageLocation) {
		this.msStorageLocation = msStorageLocation;
	}

	@Column(name = "storage_type", nullable = false, length = 3)
	public String getStorageType() {
		return this.storageType;
	}

	public void setStorageType(String storageType) {
		this.storageType = storageType;
	}

	@Column(name = "storage_bin", nullable = false, length = 10)
	public String getStorageBin() {
		return this.storageBin;
	}

	public void setStorageBin(String storageBin) {
		this.storageBin = storageBin;
	}

	@Column(name = "storage_bin_type", nullable = false, length = 2)
	public String getStorageBinType() {
		return this.storageBinType;
	}

	public void setStorageBinType(String storageBinType) {
		this.storageBinType = storageBinType;
	}

	@Column(name = "is_empty", nullable = false)
	public Boolean getIsEmpty() {
		return this.isEmpty;
	}

	public void setIsEmpty(Boolean isEmpty) {
		this.isEmpty = isEmpty;
	}

	@Column(name = "remaining_capacity", precision = 16, scale = 3)
	public BigDecimal getRemainingCapacity() {
		return this.remainingCapacity;
	}

	public void setRemainingCapacity(BigDecimal remainingCapacity) {
		this.remainingCapacity = remainingCapacity;
	}

	@Column(name = "is_deleted", nullable = false)
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "empty_bin_indicator", length = 1)
	public String getEmptyBinIndicator() {
		return this.emptyBinIndicator;
	}

	public void setEmptyBinIndicator(String emptyBinIndicator) {
		this.emptyBinIndicator = emptyBinIndicator;
	}

	@Column(name = "warehouse_number", length = 3)
	public String getWarehouseNumber() {
		return this.warehouseNumber;
	}

	public void setWarehouseNumber(String warehouseNumber) {
		this.warehouseNumber = warehouseNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "availableBin")
	public Set<AvailableBinSection> getAvailableBinSections() {
		return this.availableBinSections;
	}

	public void setAvailableBinSections(Set<AvailableBinSection> availableBinSections) {
		this.availableBinSections = availableBinSections;
	}

}
