package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MsInspection generated by hbm2java
 */
@Entity
@Table(name = "ms_inspection", schema = "bpi" )
public class MsInspection implements java.io.Serializable {

	private static final long serialVersionUID = 2620159661845577905L;

	private Integer id;
	private Integer version;
	private MsInspectionGroup msInspectionGroup;
	private String inspection;
	private String filedType;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Boolean spDisplayFlag;
	private Boolean sbDisplayFlag;
	private Integer seq;
	private Set<MsInspectionChoices> msInspectionChoiceses = new HashSet<MsInspectionChoices>(0);
	private Set<PoItemInspectionList> poItemInspectionLists = new HashSet<PoItemInspectionList>(0);

	public MsInspection() {
	}

	public MsInspection(Integer id) {
		this.id = id;
	}

	public MsInspection(Integer id, MsInspectionGroup msInspectionGroup, String inspection, String filedType,
			Boolean isDeleted, String createdBy, Date createdDate, String updatedBy, Date updatedDate,
			Boolean spDisplayFlag, Boolean sbDisplayFlag, Integer seq, Set<MsInspectionChoices> msInspectionChoiceses,
			Set<PoItemInspectionList> poItemInspectionLists) {
		this.id = id;
		this.msInspectionGroup = msInspectionGroup;
		this.inspection = inspection;
		this.filedType = filedType;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.spDisplayFlag = spDisplayFlag;
		this.sbDisplayFlag = sbDisplayFlag;
		this.seq = seq;
		this.msInspectionChoiceses = msInspectionChoiceses;
		this.poItemInspectionLists = poItemInspectionLists;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inspection_group_id")
	public MsInspectionGroup getMsInspectionGroup() {
		return this.msInspectionGroup;
	}

	public void setMsInspectionGroup(MsInspectionGroup msInspectionGroup) {
		this.msInspectionGroup = msInspectionGroup;
	}

	@Column(name = "inspection", length = 150)
	public String getInspection() {
		return this.inspection;
	}

	public void setInspection(String inspection) {
		this.inspection = inspection;
	}

	@Column(name = "filed_type", length = 100)
	public String getFiledType() {
		return this.filedType;
	}

	public void setFiledType(String filedType) {
		this.filedType = filedType;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "sp_display_flag")
	public Boolean getSpDisplayFlag() {
		return this.spDisplayFlag;
	}

	public void setSpDisplayFlag(Boolean spDisplayFlag) {
		this.spDisplayFlag = spDisplayFlag;
	}

	@Column(name = "sb_display_flag")
	public Boolean getSbDisplayFlag() {
		return this.sbDisplayFlag;
	}

	public void setSbDisplayFlag(Boolean sbDisplayFlag) {
		this.sbDisplayFlag = sbDisplayFlag;
	}

	@Column(name = "seq")
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msInspection")
	public Set<MsInspectionChoices> getMsInspectionChoiceses() {
		return this.msInspectionChoiceses;
	}

	public void setMsInspectionChoiceses(Set<MsInspectionChoices> msInspectionChoiceses) {
		this.msInspectionChoiceses = msInspectionChoiceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msInspection")
	public Set<PoItemInspectionList> getPoItemInspectionLists() {
		return this.poItemInspectionLists;
	}

	public void setPoItemInspectionLists(Set<PoItemInspectionList> poItemInspectionLists) {
		this.poItemInspectionLists = poItemInspectionLists;
	}

}
