package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MsIssueAction generated by hbm2java
 */
@Entity
@Table(name = "ms_issue_action", schema = "bpi" )
public class MsIssueAction implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private String acction;
	private Integer roleId;
	private Integer companyId;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Set<PoItemsIssuesAction> poItemsIssuesActions = new HashSet<PoItemsIssuesAction>(0);

	public MsIssueAction() {
	}

	public MsIssueAction(Integer id) {
		this.id = id;
	}

	public MsIssueAction(Integer id, String acction, Integer roleId, Integer companyId, Boolean isDeleted,
			String createdBy, Date createdDate, String updatedBy, Date updatedDate,
			Set<PoItemsIssuesAction> poItemsIssuesActions) {
		this.id = id;
		this.acction = acction;
		this.roleId = roleId;
		this.companyId = companyId;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.poItemsIssuesActions = poItemsIssuesActions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "acction", length = 50)
	public String getAcction() {
		return this.acction;
	}

	public void setAcction(String acction) {
		this.acction = acction;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msIssueAction")
	public Set<PoItemsIssuesAction> getPoItemsIssuesActions() {
		return this.poItemsIssuesActions;
	}

	public void setPoItemsIssuesActions(Set<PoItemsIssuesAction> poItemsIssuesActions) {
		this.poItemsIssuesActions = poItemsIssuesActions;
	}

}
