package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MsIssueType generated by hbm2java
 */
@Entity
@Table(name = "ms_issue_type", schema = "bpi" )
public class MsIssueType implements java.io.Serializable {

	private Integer id;
	private String issueType;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Set<PoItemsIssuesFiles> poItemsIssuesFileses = new HashSet<PoItemsIssuesFiles>(0);

	public MsIssueType() {
	}

	public MsIssueType(Integer id) {
		this.id = id;
	}

	public MsIssueType(Integer id, String issueType, Boolean isDeleted, String createdBy, Date createdDate,
			String updatedBy, Date updatedDate, Set<PoItemsIssuesFiles> poItemsIssuesFileses) {
		this.id = id;
		this.issueType = issueType;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.poItemsIssuesFileses = poItemsIssuesFileses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "issue_type", length = 200)
	public String getIssueType() {
		return this.issueType;
	}

	public void setIssueType(String issueType) {
		this.issueType = issueType;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msIssueType")
	public Set<PoItemsIssuesFiles> getPoItemsIssuesFileses() {
		return this.poItemsIssuesFileses;
	}

	public void setPoItemsIssuesFileses(Set<PoItemsIssuesFiles> poItemsIssuesFileses) {
		this.poItemsIssuesFileses = poItemsIssuesFileses;
	}

}
