package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MsIssueOption generated by hbm2java
 */
@Entity
@Table(name = "ms_issue_option", schema = "bpi" )
public class MsIssueOption implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private String status;
	private Integer companyId;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Set<PoItemsIssues> poItemsIssueses = new HashSet<PoItemsIssues>(0);
	private Set<PoItemsIssues> poItemsIssueses_1 = new HashSet<PoItemsIssues>(0);

	public MsIssueOption() {
	}

	public MsIssueOption(Integer id) {
		this.id = id;
	}

	public MsIssueOption(Integer id, String status, Integer companyId, Boolean isDeleted, String createdBy,
			Date createdDate, String updatedBy, Date updatedDate, Set<PoItemsIssues> poItemsIssueses,
			Set<PoItemsIssues> poItemsIssueses_1) {
		this.id = id;
		this.status = status;
		this.companyId = companyId;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.poItemsIssueses = poItemsIssueses;
		this.poItemsIssueses_1 = poItemsIssueses_1;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "status", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "company_id")
	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msIssueOption")
	public Set<PoItemsIssues> getPoItemsIssueses() {
		return this.poItemsIssueses;
	}

	public void setPoItemsIssueses(Set<PoItemsIssues> poItemsIssueses) {
		this.poItemsIssueses = poItemsIssueses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msIssueOption")
	public Set<PoItemsIssues> getPoItemsIssueses_1() {
		return this.poItemsIssueses_1;
	}

	public void setPoItemsIssueses_1(Set<PoItemsIssues> poItemsIssueses_1) {
		this.poItemsIssueses_1 = poItemsIssueses_1;
	}

}
