package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MsPlant generated by hbm2java
 */
@Entity
@Table(name = "ms_plant", schema = "bpi" )
public class MsPlant implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private String plant;
	private String plantName;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Set<AvailableBin> availableBins = new HashSet<AvailableBin>(0);
	private Set<PoItemsQiRelease> poItemsQiReleases = new HashSet<PoItemsQiRelease>(0);
	private Set<MsStorageLocation> msStorageLocations = new HashSet<MsStorageLocation>(0);
	private Set<MaterialIdentity> materialIdentities = new HashSet<MaterialIdentity>(0);
	private Set<PoItems> poItemses = new HashSet<PoItems>(0);
	private Set<PoItemsQi> poItemsQis = new HashSet<PoItemsQi>(0);

	public MsPlant() {
	}

	public MsPlant(Integer id, Boolean isDeleted, String createdBy, Date createdDate) {
		this.id = id;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public MsPlant(Integer id, String plant, String plantName, Boolean isDeleted, String createdBy,
			Date createdDate, String updatedBy, Date updatedDate, Set<AvailableBin> availableBins,
			Set<PoItemsQiRelease> poItemsQiReleases, Set<MsStorageLocation> msStorageLocations,
			Set<MaterialIdentity> materialIdentities, Set<PoItems> poItemses, Set<PoItemsQi> poItemsQis) {
		this.id = id;
		this.plant = plant;
		this.plantName = plantName;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.availableBins = availableBins;
		this.poItemsQiReleases = poItemsQiReleases;
		this.msStorageLocations = msStorageLocations;
		this.materialIdentities = materialIdentities;
		this.poItemses = poItemses;
		this.poItemsQis = poItemsQis;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "plant", length = 4)
	public String getPlant() {
		return this.plant;
	}

	public void setPlant(String plant) {
		this.plant = plant;
	}

	@Column(name = "plant_name", length = 150)
	public String getPlantName() {
		return this.plantName;
	}

	public void setPlantName(String plantName) {
		this.plantName = plantName;
	}

	@Column(name = "is_deleted", nullable = false)
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msPlant")
	public Set<AvailableBin> getAvailableBins() {
		return this.availableBins;
	}

	public void setAvailableBins(Set<AvailableBin> availableBins) {
		this.availableBins = availableBins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msPlant")
	public Set<PoItemsQiRelease> getPoItemsQiReleases() {
		return this.poItemsQiReleases;
	}

	public void setPoItemsQiReleases(Set<PoItemsQiRelease> poItemsQiReleases) {
		this.poItemsQiReleases = poItemsQiReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msPlant")
	public Set<MsStorageLocation> getMsStorageLocations() {
		return this.msStorageLocations;
	}

	public void setMsStorageLocations(Set<MsStorageLocation> msStorageLocations) {
		this.msStorageLocations = msStorageLocations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msPlant")
	public Set<PoItems> getPoItemses() {
		return this.poItemses;
	}

	public void setPoItemses(Set<PoItems> poItemses) {
		this.poItemses = poItemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "msPlant")
	public Set<PoItemsQi> getPoItemsQis() {
		return this.poItemsQis;
	}

	public void setPoItemsQis(Set<PoItemsQi> poItemsQis) {
		this.poItemsQis = poItemsQis;
	}

}
