package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Po generated by hbm2java
 */
@Entity
@Table(name = "po", schema = "bpi" )
public class Po implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private MsReturnStatus msReturnStatus;
	private PoStatus poStatus;
	private PoType poType;
	private Supplier supplier;
	private String poNumber;
	private Date poDate;
	private String companyCode;
	private Boolean isClosed;
	private Date closedDate;
	private String closedBy;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private String poTypeDescription;
	private Set<PoMatchItems> poMatchItemsesForSpPoId = new HashSet<PoMatchItems>(0);
	private Set<PoItemsConfirmation> poItemsConfirmations = new HashSet<PoItemsConfirmation>(0);
	private Set<PoMatchItems> poMatchItemsesForSbPoId = new HashSet<PoMatchItems>(0);
	private Set<PoItems> poItemses = new HashSet<PoItems>(0);
	private Set<PoItemsIssues> poItemsIssueses = new HashSet<PoItemsIssues>(0);

	public Po() {
	}

	public Po(Integer id) {
		this.id = id;
	}

	public Po(Integer id, MsReturnStatus msReturnStatus, PoStatus poStatus, PoType poType, Supplier supplier,
			String poNumber, Date poDate, String companyCode, Boolean isClosed, Date closedDate,
			String closedBy, Boolean isDeleted, String createdBy, Date createdDate, String updatedBy, Date updatedDate,
			String poTypeDescription,
			Set<PoMatchItems> poMatchItemsesForSpPoId, Set<PoItemsConfirmation> poItemsConfirmations,
			Set<PoMatchItems> poMatchItemsesForSbPoId,
			 Set<PoItems> poItemses,
			Set<PoItemsIssues> poItemsIssueses) {
		this.id = id;
		this.msReturnStatus = msReturnStatus;
		this.poStatus = poStatus;
		this.poType = poType;
		this.supplier = supplier;
		this.poNumber = poNumber;
		this.poDate = poDate;
		this.companyCode = companyCode;
		this.isClosed = isClosed;
		this.closedDate = closedDate;
		this.closedBy = closedBy;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.poTypeDescription = poTypeDescription;
		this.poMatchItemsesForSpPoId = poMatchItemsesForSpPoId;
		this.poItemsConfirmations = poItemsConfirmations;
		this.poMatchItemsesForSbPoId = poMatchItemsesForSbPoId;
		this.poItemses = poItemses;
		this.poItemsIssueses = poItemsIssueses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "return_status_id")
	public MsReturnStatus getMsReturnStatus() {
		return this.msReturnStatus;
	}

	public void setMsReturnStatus(MsReturnStatus msReturnStatus) {
		this.msReturnStatus = msReturnStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_status_id")
	public PoStatus getPoStatus() {
		return this.poStatus;
	}

	public void setPoStatus(PoStatus poStatus) {
		this.poStatus = poStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_type_id")
	public PoType getPoType() {
		return this.poType;
	}

	public void setPoType(PoType poType) {
		this.poType = poType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_id")
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@Column(name = "po_number", length = 10)
	public String getPoNumber() {
		return this.poNumber;
	}

	public void setPoNumber(String poNumber) {
		this.poNumber = poNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "po_date", length = 10)
	public Date getPoDate() {
		return this.poDate;
	}

	public void setPoDate(Date poDate) {
		this.poDate = poDate;
	}

	@Column(name = "company_code", length = 4)
	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	@Column(name = "is_closed")
	public Boolean getIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(Boolean isClosed) {
		this.isClosed = isClosed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "closed_date", length = 23)
	public Date getClosedDate() {
		return this.closedDate;
	}

	public void setClosedDate(Date closedDate) {
		this.closedDate = closedDate;
	}

	@Column(name = "closed_by", length = 50)
	public String getClosedBy() {
		return this.closedBy;
	}

	public void setClosedBy(String closedBy) {
		this.closedBy = closedBy;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "po_type_description")
	public String getPoTypeDescription() {
		return this.poTypeDescription;
	}

	public void setPoTypeDescription(String poTypeDescription) {
		this.poTypeDescription = poTypeDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poBySpPoId")
	public Set<PoMatchItems> getPoMatchItemsesForSpPoId() {
		return this.poMatchItemsesForSpPoId;
	}

	public void setPoMatchItemsesForSpPoId(Set<PoMatchItems> poMatchItemsesForSpPoId) {
		this.poMatchItemsesForSpPoId = poMatchItemsesForSpPoId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "po")
	public Set<PoItemsConfirmation> getPoItemsConfirmations() {
		return this.poItemsConfirmations;
	}

	public void setPoItemsConfirmations(Set<PoItemsConfirmation> poItemsConfirmations) {
		this.poItemsConfirmations = poItemsConfirmations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poBySbPoId")
	public Set<PoMatchItems> getPoMatchItemsesForSbPoId() {
		return this.poMatchItemsesForSbPoId;
	}

	public void setPoMatchItemsesForSbPoId(Set<PoMatchItems> poMatchItemsesForSbPoId) {
		this.poMatchItemsesForSbPoId = poMatchItemsesForSbPoId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "po")
	public Set<PoItems> getPoItemses() {
		return this.poItemses;
	}

	public void setPoItemses(Set<PoItems> poItemses) {
		this.poItemses = poItemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "po")
	public Set<PoItemsIssues> getPoItemsIssueses() {
		return this.poItemsIssueses;
	}

	public void setPoItemsIssueses(Set<PoItemsIssues> poItemsIssueses) {
		this.poItemsIssueses = poItemsIssueses;
	}


}
