package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PoItemsQi generated by hbm2java
 */
@Entity
@Table(name = "po_items_qi", schema = "bpi" )
public class PoItemsQi implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private MsPlant msPlant;
	private MsQiReason msQiReason;
	private MsStockType msStockType;
	private MsStorageLocation msStorageLocation;
	private PoItems poItems;
	private PoItemsSchedule poItemsSchedule;
	private PoType poType;
	private BigDecimal materialQuantity;
	private String batch;
	private String venderBatch;
	private Date qiDate;
	private String otherReason;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Integer spReceiveItemsBatchId;
	private Set<PoItemsQiRelease> poItemsQiReleases = new HashSet<PoItemsQiRelease>(0);
	private Set<PoItemsQiReasonTr> poItemsQiReasonTrs = new HashSet<PoItemsQiReasonTr>(0);

	public PoItemsQi() {
	}

	public PoItemsQi(Integer id, MsPlant msPlant, MsStockType msStockType, MsStorageLocation msStorageLocation,
			PoItems poItems, BigDecimal materialQuantity, String batch, Boolean isDeleted, String createdBy,
			Date createdDate) {
		this.id = id;
		this.msPlant = msPlant;
		this.msStockType = msStockType;
		this.msStorageLocation = msStorageLocation;
		this.poItems = poItems;
		this.materialQuantity = materialQuantity;
		this.batch = batch;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public PoItemsQi(Integer id, MsPlant msPlant, MsQiReason msQiReason, MsStockType msStockType,
			MsStorageLocation msStorageLocation, PoItems poItems, PoItemsSchedule poItemsSchedule, PoType poType,
			BigDecimal materialQuantity, String batch, String venderBatch, Date qiDate,
			String otherReason, Boolean isDeleted, String createdBy, Date createdDate, String updatedBy,
			Date updatedDate, Integer spReceiveItemsBatchId, Set<PoItemsQiRelease> poItemsQiReleases,
			Set<PoItemsQiReasonTr> poItemsQiReasonTrs) {
		this.id = id;
		this.msPlant = msPlant;
		this.msQiReason = msQiReason;
		this.msStockType = msStockType;
		this.msStorageLocation = msStorageLocation;
		this.poItems = poItems;
		this.poItemsSchedule = poItemsSchedule;
		this.poType = poType;
		this.materialQuantity = materialQuantity;
		this.batch = batch;
		this.venderBatch = venderBatch;
		this.qiDate = qiDate;
		this.otherReason = otherReason;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.spReceiveItemsBatchId = spReceiveItemsBatchId;
		this.poItemsQiReleases = poItemsQiReleases;
		this.poItemsQiReasonTrs = poItemsQiReasonTrs;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plant_id", nullable = false)
	public MsPlant getMsPlant() {
		return this.msPlant;
	}

	public void setMsPlant(MsPlant msPlant) {
		this.msPlant = msPlant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "qi_reason_id")
	public MsQiReason getMsQiReason() {
		return this.msQiReason;
	}

	public void setMsQiReason(MsQiReason msQiReason) {
		this.msQiReason = msQiReason;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stock_type_id", nullable = false)
	public MsStockType getMsStockType() {
		return this.msStockType;
	}

	public void setMsStockType(MsStockType msStockType) {
		this.msStockType = msStockType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "storage_location_id", nullable = false)
	public MsStorageLocation getMsStorageLocation() {
		return this.msStorageLocation;
	}

	public void setMsStorageLocation(MsStorageLocation msStorageLocation) {
		this.msStorageLocation = msStorageLocation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_item_id", nullable = false)
	public PoItems getPoItems() {
		return this.poItems;
	}

	public void setPoItems(PoItems poItems) {
		this.poItems = poItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_schedule_id")
	public PoItemsSchedule getPoItemsSchedule() {
		return this.poItemsSchedule;
	}

	public void setPoItemsSchedule(PoItemsSchedule poItemsSchedule) {
		this.poItemsSchedule = poItemsSchedule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_type_id")
	public PoType getPoType() {
		return this.poType;
	}

	public void setPoType(PoType poType) {
		this.poType = poType;
	}

	@Column(name = "material_quantity", nullable = false, precision = 16, scale = 3)
	public BigDecimal getMaterialQuantity() {
		return this.materialQuantity;
	}

	public void setMaterialQuantity(BigDecimal materialQuantity) {
		this.materialQuantity = materialQuantity;
	}

	@Column(name = "batch", nullable = false, length = 10)
	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	@Column(name = "vender_batch", length = 50)
	public String getVenderBatch() {
		return this.venderBatch;
	}

	public void setVenderBatch(String venderBatch) {
		this.venderBatch = venderBatch;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "qi_date", length = 23)
	public Date getQiDate() {
		return this.qiDate;
	}

	public void setQiDate(Date qiDate) {
		this.qiDate = qiDate;
	}

	@Column(name = "other_reason", length = 500)
	public String getOtherReason() {
		return this.otherReason;
	}

	public void setOtherReason(String otherReason) {
		this.otherReason = otherReason;
	}

	@Column(name = "is_deleted", nullable = false)
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "sp_receive_items_batch_id")
	public Integer getSpReceiveItemsBatchId() {
		return this.spReceiveItemsBatchId;
	}

	public void setSpReceiveItemsBatchId(Integer spReceiveItemsBatchId) {
		this.spReceiveItemsBatchId = spReceiveItemsBatchId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poItemsQi")
	public Set<PoItemsQiRelease> getPoItemsQiReleases() {
		return this.poItemsQiReleases;
	}

	public void setPoItemsQiReleases(Set<PoItemsQiRelease> poItemsQiReleases) {
		this.poItemsQiReleases = poItemsQiReleases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poItemsQi")
	public Set<PoItemsQiReasonTr> getPoItemsQiReasonTrs() {
		return this.poItemsQiReasonTrs;
	}

	public void setPoItemsQiReasonTrs(Set<PoItemsQiReasonTr> poItemsQiReasonTrs) {
		this.poItemsQiReasonTrs = poItemsQiReasonTrs;
	}

}
