package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;

/**
 * PoItemsIssuesFiles generated by hbm2java
 */
@Entity
@Table(name = "po_items_issues_files", schema = "bpi" )
public class PoItemsIssuesFiles implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private MsIssueSteps msIssueSteps;
	private MsIssueType msIssueType;
	private PoItemsIssues poItemsIssues;
	private String otherIssueTypeDesc;
	private String fileName;
	private String linkFile;
	private byte[] data;
	private String contentType;
	private Integer size;
	private Integer receiveIssueId;
	private String issueDetail;
	private String expectedCause;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public PoItemsIssuesFiles() {
	}

	public PoItemsIssuesFiles(Integer id) {
		this.id = id;
	}

	public PoItemsIssuesFiles(Integer id, MsIssueSteps msIssueSteps, MsIssueType msIssueType,
			PoItemsIssues poItemsIssues, String otherIssueTypeDesc, String fileName, String linkFile, byte[] data,
			String contentType, Integer size, Integer receiveIssueId, String issueDetail, String expectedCause,
			Boolean isDeleted, String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
		this.id = id;
		this.msIssueSteps = msIssueSteps;
		this.msIssueType = msIssueType;
		this.poItemsIssues = poItemsIssues;
		this.otherIssueTypeDesc = otherIssueTypeDesc;
		this.fileName = fileName;
		this.linkFile = linkFile;
		this.data = data;
		this.contentType = contentType;
		this.size = size;
		this.receiveIssueId = receiveIssueId;
		this.issueDetail = issueDetail;
		this.expectedCause = expectedCause;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "issue_steps_id")
	public MsIssueSteps getMsIssueSteps() {
		return this.msIssueSteps;
	}

	public void setMsIssueSteps(MsIssueSteps msIssueSteps) {
		this.msIssueSteps = msIssueSteps;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "issue_type_id")
	public MsIssueType getMsIssueType() {
		return this.msIssueType;
	}

	public void setMsIssueType(MsIssueType msIssueType) {
		this.msIssueType = msIssueType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_issues_id")
	public PoItemsIssues getPoItemsIssues() {
		return this.poItemsIssues;
	}

	public void setPoItemsIssues(PoItemsIssues poItemsIssues) {
		this.poItemsIssues = poItemsIssues;
	}

	@Column(name = "other_issue_type_desc", length = 300)
	public String getOtherIssueTypeDesc() {
		return this.otherIssueTypeDesc;
	}

	public void setOtherIssueTypeDesc(String otherIssueTypeDesc) {
		this.otherIssueTypeDesc = otherIssueTypeDesc;
	}

	@Column(name = "file_name", length = 100)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "link_file", length = 550)
	public String getLinkFile() {
		return this.linkFile;
	}

	public void setLinkFile(String linkFile) {
		this.linkFile = linkFile;
	}

	@Column(name = "data")
	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	@Column(name = "content_type")
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "size")
	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	@Column(name = "receive_issue_id")
	public Integer getReceiveIssueId() {
		return this.receiveIssueId;
	}

	public void setReceiveIssueId(Integer receiveIssueId) {
		this.receiveIssueId = receiveIssueId;
	}

	@Column(name = "issue_detail", length = 1000)
	public String getIssueDetail() {
		return this.issueDetail;
	}

	public void setIssueDetail(String issueDetail) {
		this.issueDetail = issueDetail;
	}

	@Column(name = "expected_cause", length = 500)
	public String getExpectedCause() {
		return this.expectedCause;
	}

	public void setExpectedCause(String expectedCause) {
		this.expectedCause = expectedCause;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
