package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;

/**
 * PoItemsQiReasonTr generated by hbm2java
 */
@Entity
@Table(name = "po_items_qi_reason_tr", schema = "bpi" )
public class PoItemsQiReasonTr implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private MsQiReason msQiReason;
	private PoItemsQi poItemsQi;
	private String otherReason;
	private String reasonBy;
	private Date reasonDate;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private String remark;

	public PoItemsQiReasonTr() {
	}

	public PoItemsQiReasonTr(Integer id, String createdBy, Date createdDate) {
		this.id = id;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public PoItemsQiReasonTr(Integer id, MsQiReason msQiReason, PoItemsQi poItemsQi, String otherReason,
			String reasonBy, Date reasonDate, Boolean isDeleted, String createdBy, Date createdDate, String updatedBy,
			Date updatedDate, String remark) {
		this.id = id;
		this.msQiReason = msQiReason;
		this.poItemsQi = poItemsQi;
		this.otherReason = otherReason;
		this.reasonBy = reasonBy;
		this.reasonDate = reasonDate;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.remark = remark;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ms_reason_id")
	public MsQiReason getMsQiReason() {
		return this.msQiReason;
	}

	public void setMsQiReason(MsQiReason msQiReason) {
		this.msQiReason = msQiReason;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_qi_id")
	public PoItemsQi getPoItemsQi() {
		return this.poItemsQi;
	}

	public void setPoItemsQi(PoItemsQi poItemsQi) {
		this.poItemsQi = poItemsQi;
	}

	@Column(name = "other_reason")
	public String getOtherReason() {
		return this.otherReason;
	}

	public void setOtherReason(String otherReason) {
		this.otherReason = otherReason;
	}

	@Column(name = "reason_by", length = 50)
	public String getReasonBy() {
		return this.reasonBy;
	}

	public void setReasonBy(String reasonBy) {
		this.reasonBy = reasonBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reason_date", length = 23)
	public Date getReasonDate() {
		return this.reasonDate;
	}

	public void setReasonDate(Date reasonDate) {
		this.reasonDate = reasonDate;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "remark", length = 1250)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
