package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PoItemInspection generated by hbm2java
 */
@Entity
@Table(name = "po_item_inspection", schema = "bpi" )
public class PoItemInspection implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private PoItems poItems;
	private PoItemsConfirmation poItemsConfirmation;
	private PoItemsSchedule poItemsSchedule;
	private Date receivingDate;
	private String driverName;
	private Boolean inspectionStatus;
	private String materialDocument;
	private String sendingTime;
	private String licensePlate;
	private String specialLicensePlate;
	private String phoneNumber;
	private Boolean hasIncident;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Set<PoItemInspectionList> poItemInspectionLists = new HashSet<PoItemInspectionList>(0);
	public PoItemInspection() {
	}

	public PoItemInspection(Integer id) {
		this.id = id;
	}

	public PoItemInspection(Integer id, PoItems poItems, PoItemsConfirmation poItemsConfirmation,
			PoItemsSchedule poItemsSchedule, Date receivingDate, String driverName,
			Boolean inspectionStatus, String materialDocument, String sendingTime, String licensePlate,
			String specialLicensePlate, String phoneNumber, Boolean hasIncident, Boolean isDeleted, String createdBy,
			Date createdDate, String updatedBy, Date updatedDate,
			Set<PoItemInspectionList> poItemInspectionLists) {
		this.id = id;
		this.poItems = poItems;
		this.poItemsConfirmation = poItemsConfirmation;
		this.poItemsSchedule = poItemsSchedule;
		this.receivingDate = receivingDate;
		this.driverName = driverName;
		this.inspectionStatus = inspectionStatus;
		this.materialDocument = materialDocument;
		this.sendingTime = sendingTime;
		this.licensePlate = licensePlate;
		this.specialLicensePlate = specialLicensePlate;
		this.phoneNumber = phoneNumber;
		this.hasIncident = hasIncident;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.poItemInspectionLists = poItemInspectionLists;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_id")
	public PoItems getPoItems() {
		return this.poItems;
	}

	public void setPoItems(PoItems poItems) {
		this.poItems = poItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_confirmation_id")
	public PoItemsConfirmation getPoItemsConfirmation() {
		return this.poItemsConfirmation;
	}

	public void setPoItemsConfirmation(PoItemsConfirmation poItemsConfirmation) {
		this.poItemsConfirmation = poItemsConfirmation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_schedule_id")
	public PoItemsSchedule getPoItemsSchedule() {
		return this.poItemsSchedule;
	}

	public void setPoItemsSchedule(PoItemsSchedule poItemsSchedule) {
		this.poItemsSchedule = poItemsSchedule;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "receiving_date", length = 10)
	public Date getReceivingDate() {
		return this.receivingDate;
	}

	public void setReceivingDate(Date receivingDate) {
		this.receivingDate = receivingDate;
	}

	@Column(name = "driver_name", length = 150)
	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	@Column(name = "inspection_status")
	public Boolean getInspectionStatus() {
		return this.inspectionStatus;
	}

	public void setInspectionStatus(Boolean inspectionStatus) {
		this.inspectionStatus = inspectionStatus;
	}

	@Column(name = "material_document")
	public String getMaterialDocument() {
		return this.materialDocument;
	}

	public void setMaterialDocument(String materialDocument) {
		this.materialDocument = materialDocument;
	}

	@Column(name = "sending_time", length = 7)
	public String getSendingTime() {
		return this.sendingTime;
	}

	public void setSendingTime(String sendingTime) {
		this.sendingTime = sendingTime;
	}

	@Column(name = "license_plate", length = 10)
	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	@Column(name = "special_license_plate", length = 10)
	public String getSpecialLicensePlate() {
		return this.specialLicensePlate;
	}

	public void setSpecialLicensePlate(String specialLicensePlate) {
		this.specialLicensePlate = specialLicensePlate;
	}

	@Column(name = "phone_number", length = 15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "has_incident")
	public Boolean getHasIncident() {
		return this.hasIncident;
	}

	public void setHasIncident(Boolean hasIncident) {
		this.hasIncident = hasIncident;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poItemInspection")
	public Set<PoItemInspectionList> getPoItemInspectionLists() {
		return this.poItemInspectionLists;
	}

	public void setPoItemInspectionLists(Set<PoItemInspectionList> poItemInspectionLists) {
		this.poItemInspectionLists = poItemInspectionLists;
	}


}
