package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;

/**
 * PoItemsConfirmationDnBatch generated by hbm2java
 */
@Entity
@Table(name = "po_items_confirmation_dn_batch", schema = "bpi" )
public class PoItemsConfirmationDnBatch implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private PoItems poItems;
	private PoItemsBatch poItemsBatch;
	private PoItemsConfirmation poItemsConfirmation;
	private Integer lineItem;
	private String deliveryNote;
	private String batch;
	private String changeRemark;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public PoItemsConfirmationDnBatch() {
	}

	public PoItemsConfirmationDnBatch(Integer id, PoItemsConfirmation poItemsConfirmation, Integer lineItem,
			Boolean isDeleted, String createdBy, Date createdDate) {
		this.id = id;
		this.poItemsConfirmation = poItemsConfirmation;
		this.lineItem = lineItem;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public PoItemsConfirmationDnBatch(Integer id, PoItems poItems, PoItemsBatch poItemsBatch,
			PoItemsConfirmation poItemsConfirmation, Integer lineItem, String deliveryNote, String batch,
			String changeRemark, Boolean isDeleted, String createdBy, Date createdDate, String updatedBy,
			Date updatedDate) {
		this.id = id;
		this.poItems = poItems;
		this.poItemsBatch = poItemsBatch;
		this.poItemsConfirmation = poItemsConfirmation;
		this.lineItem = lineItem;
		this.deliveryNote = deliveryNote;
		this.batch = batch;
		this.changeRemark = changeRemark;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_id")
	public PoItems getPoItems() {
		return this.poItems;
	}

	public void setPoItems(PoItems poItems) {
		this.poItems = poItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_batch_id")
	public PoItemsBatch getPoItemsBatch() {
		return this.poItemsBatch;
	}

	public void setPoItemsBatch(PoItemsBatch poItemsBatch) {
		this.poItemsBatch = poItemsBatch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_confirmation_id", nullable = false)
	public PoItemsConfirmation getPoItemsConfirmation() {
		return this.poItemsConfirmation;
	}

	public void setPoItemsConfirmation(PoItemsConfirmation poItemsConfirmation) {
		this.poItemsConfirmation = poItemsConfirmation;
	}

	@Column(name = "line_item", nullable = false)
	public Integer getLineItem() {
		return this.lineItem;
	}

	public void setLineItem(Integer lineItem) {
		this.lineItem = lineItem;
	}

	@Column(name = "delivery_note", length = 30)
	public String getDeliveryNote() {
		return this.deliveryNote;
	}

	public void setDeliveryNote(String deliveryNote) {
		this.deliveryNote = deliveryNote;
	}

	@Column(name = "batch", length = 30)
	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	@Column(name = "change_remark", length = 250)
	public String getChangeRemark() {
		return this.changeRemark;
	}

	public void setChangeRemark(String changeRemark) {
		this.changeRemark = changeRemark;
	}

	@Column(name = "is_deleted", nullable = false)
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
