package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;

/**
 * PoItemsQiReleaseMessage generated by hbm2java
 */
@Entity
@Table(name = "po_items_qi_release_message", schema = "bpi" )
public class PoItemsQiReleaseMessage implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private PoItemsQiRelease poItemsQiRelease;
	private Integer fileSeq;
	private Date fileDate;
	private String companyCode;
	private String messageCode;
	private String messageType;
	private String messageId;
	private String messageNo;
	private String message1;
	private String message2;
	private String message3;
	private String message4;
	private String remark;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public PoItemsQiReleaseMessage() {
	}

	public PoItemsQiReleaseMessage(Integer id, PoItemsQiRelease poItemsQiRelease, Integer fileSeq, Date fileDate,
			String messageCode, String messageType, String message1) {
		this.id = id;
		this.poItemsQiRelease = poItemsQiRelease;
		this.fileSeq = fileSeq;
		this.fileDate = fileDate;
		this.messageCode = messageCode;
		this.messageType = messageType;
		this.message1 = message1;
	}

	public PoItemsQiReleaseMessage(Integer id, PoItemsQiRelease poItemsQiRelease, Integer fileSeq, Date fileDate,
			String companyCode, String messageCode, String messageType, String messageId, String messageNo,
			String message1, String message2, String message3, String message4, String remark, Boolean isDeleted,
			String createdBy, Date createdDate, String updatedBy, Date updatedDate) {
		this.id = id;
		this.poItemsQiRelease = poItemsQiRelease;
		this.fileSeq = fileSeq;
		this.fileDate = fileDate;
		this.companyCode = companyCode;
		this.messageCode = messageCode;
		this.messageType = messageType;
		this.messageId = messageId;
		this.messageNo = messageNo;
		this.message1 = message1;
		this.message2 = message2;
		this.message3 = message3;
		this.message4 = message4;
		this.remark = remark;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_qi_release_id", nullable = false)
	public PoItemsQiRelease getPoItemsQiRelease() {
		return this.poItemsQiRelease;
	}

	public void setPoItemsQiRelease(PoItemsQiRelease poItemsQiRelease) {
		this.poItemsQiRelease = poItemsQiRelease;
	}

	@Column(name = "file_seq", nullable = false)
	public Integer getFileSeq() {
		return this.fileSeq;
	}

	public void setFileSeq(Integer fileSeq) {
		this.fileSeq = fileSeq;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "file_date", nullable = false, length = 10)
	public Date getFileDate() {
		return this.fileDate;
	}

	public void setFileDate(Date fileDate) {
		this.fileDate = fileDate;
	}

	@Column(name = "company_code", length = 4)
	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	@Column(name = "message_code", nullable = false, length = 10)
	public String getMessageCode() {
		return this.messageCode;
	}

	public void setMessageCode(String messageCode) {
		this.messageCode = messageCode;
	}

	@Column(name = "message_type", nullable = false, length = 1)
	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	@Column(name = "message_id", length = 10)
	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "message_no", length = 10)
	public String getMessageNo() {
		return this.messageNo;
	}

	public void setMessageNo(String messageNo) {
		this.messageNo = messageNo;
	}

	@Column(name = "message1", nullable = false, length = 510)
	public String getMessage1() {
		return this.message1;
	}

	public void setMessage1(String message1) {
		this.message1 = message1;
	}

	@Column(name = "message2", length = 510)
	public String getMessage2() {
		return this.message2;
	}

	public void setMessage2(String message2) {
		this.message2 = message2;
	}

	@Column(name = "message3", length = 510)
	public String getMessage3() {
		return this.message3;
	}

	public void setMessage3(String message3) {
		this.message3 = message3;
	}

	@Column(name = "message4", length = 510)
	public String getMessage4() {
		return this.message4;
	}

	public void setMessage4(String message4) {
		this.message4 = message4;
	}

	@Column(name = "remark", length = 510)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
