package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PoItemsBatch generated by hbm2java
 */
@Entity
@Table(name = "po_items_batch", schema = "bpi" )
public class PoItemsBatch implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private Material material;
	private PoItems poItems;
	private String batch;
	private Date manufactureDate;
	private Date expireDate;
	private String countryOfOrigin;
	private String manufacturer;
	private String changeRemark;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Set<PoItemsConfirmationDnBatch> poItemsConfirmationDnBatches = new HashSet<PoItemsConfirmationDnBatch>(0);
	private Set<PoItemsScheduleDnBatch> poItemsScheduleDnBatches = new HashSet<PoItemsScheduleDnBatch>(0);

	public PoItemsBatch() {
	}

	public PoItemsBatch(Integer id, Boolean isDeleted, Date createdDate) {
		this.id = id;
		this.isDeleted = isDeleted;
		this.createdDate = createdDate;
	}

	public PoItemsBatch(Integer id, Material material, PoItems poItems, String batch, Date manufactureDate,
			Date expireDate, String countryOfOrigin, String manufacturer, String changeRemark, Boolean isDeleted,
			String createdBy, Date createdDate, String updatedBy, Date updatedDate,
			Set<PoItemsConfirmationDnBatch> poItemsConfirmationDnBatches,
			Set<PoItemsScheduleDnBatch> poItemsScheduleDnBatches) {
		this.id = id;
		this.material = material;
		this.poItems = poItems;
		this.batch = batch;
		this.manufactureDate = manufactureDate;
		this.expireDate = expireDate;
		this.countryOfOrigin = countryOfOrigin;
		this.manufacturer = manufacturer;
		this.changeRemark = changeRemark;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.poItemsConfirmationDnBatches = poItemsConfirmationDnBatches;
		this.poItemsScheduleDnBatches = poItemsScheduleDnBatches;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "material_id")
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_id")
	public PoItems getPoItems() {
		return this.poItems;
	}

	public void setPoItems(PoItems poItems) {
		this.poItems = poItems;
	}

	@Column(name = "batch", length = 10)
	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "manufacture_date", length = 10)
	public Date getManufactureDate() {
		return this.manufactureDate;
	}

	public void setManufactureDate(Date manufactureDate) {
		this.manufactureDate = manufactureDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expire_date", length = 10)
	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	@Column(name = "country_of_origin", length = 30)
	public String getCountryOfOrigin() {
		return this.countryOfOrigin;
	}

	public void setCountryOfOrigin(String countryOfOrigin) {
		this.countryOfOrigin = countryOfOrigin;
	}

	@Column(name = "manufacturer", length = 30)
	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	@Column(name = "change_remark", length = 250)
	public String getChangeRemark() {
		return this.changeRemark;
	}

	public void setChangeRemark(String changeRemark) {
		this.changeRemark = changeRemark;
	}

	@Column(name = "is_deleted", nullable = false)
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poItemsBatch")
	public Set<PoItemsConfirmationDnBatch> getPoItemsConfirmationDnBatches() {
		return this.poItemsConfirmationDnBatches;
	}

	public void setPoItemsConfirmationDnBatches(Set<PoItemsConfirmationDnBatch> poItemsConfirmationDnBatches) {
		this.poItemsConfirmationDnBatches = poItemsConfirmationDnBatches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poItemsBatch")
	public Set<PoItemsScheduleDnBatch> getPoItemsScheduleDnBatches() {
		return this.poItemsScheduleDnBatches;
	}

	public void setPoItemsScheduleDnBatches(Set<PoItemsScheduleDnBatch> poItemsScheduleDnBatches) {
		this.poItemsScheduleDnBatches = poItemsScheduleDnBatches;
	}

}
