package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PoItemsConfirmation generated by hbm2java
 */
@Entity
@Table(name = "po_items_confirmation", schema = "bpi" )
public class PoItemsConfirmation implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private Po po;
	private PoItems poItems;
	private Integer lineItem;
	private Integer seqNo;
	private Date deliveryDate;
	private BigDecimal confirmationQty;
	private BigDecimal reducedQty;
	private Boolean isClosed;
	private Date closedDate;
	private String closedBy;
	private String changeRemark;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Set<PoItemsConfirmationDnBatch> poItemsConfirmationDnBatches = new HashSet<PoItemsConfirmationDnBatch>(0);
	private Set<PoItemsIssues> poItemsIssueses = new HashSet<PoItemsIssues>(0);
	private Set<PoItemInspection> poItemInspections = new HashSet<PoItemInspection>(0);

	public PoItemsConfirmation() {
	}

	public PoItemsConfirmation(Integer id, Po po, Integer lineItem, Integer seqNo, Date deliveryDate,
			BigDecimal confirmationQty, Boolean isDeleted, String createdBy, Date createdDate) {
		this.id = id;
		this.po = po;
		this.lineItem = lineItem;
		this.seqNo = seqNo;
		this.deliveryDate = deliveryDate;
		this.confirmationQty = confirmationQty;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public PoItemsConfirmation(Integer id, Po po, PoItems poItems, Integer lineItem, Integer seqNo, Date deliveryDate,
			BigDecimal confirmationQty, BigDecimal reducedQty, Boolean isClosed, Date closedDate, String closedBy,
			String changeRemark, Boolean isDeleted, String createdBy, Date createdDate, String updatedBy,
			Date updatedDate,
			Set<PoItemsConfirmationDnBatch> poItemsConfirmationDnBatches, Set<PoItemsIssues> poItemsIssueses,
			Set<PoItemInspection> poItemInspections) {
		this.id = id;
		this.po = po;
		this.poItems = poItems;
		this.lineItem = lineItem;
		this.seqNo = seqNo;
		this.deliveryDate = deliveryDate;
		this.confirmationQty = confirmationQty;
		this.reducedQty = reducedQty;
		this.isClosed = isClosed;
		this.closedDate = closedDate;
		this.closedBy = closedBy;
		this.changeRemark = changeRemark;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.poItemsConfirmationDnBatches = poItemsConfirmationDnBatches;
		this.poItemsIssueses = poItemsIssueses;
		this.poItemInspections = poItemInspections;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_id", nullable = false)
	public Po getPo() {
		return this.po;
	}

	public void setPo(Po po) {
		this.po = po;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_id")
	public PoItems getPoItems() {
		return this.poItems;
	}

	public void setPoItems(PoItems poItems) {
		this.poItems = poItems;
	}

	@Column(name = "line_item", nullable = false)
	public Integer getLineItem() {
		return this.lineItem;
	}

	public void setLineItem(Integer lineItem) {
		this.lineItem = lineItem;
	}

	@Column(name = "seq_no", nullable = false)
	public Integer getSeqNo() {
		return this.seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "delivery_date", nullable = false, length = 10)
	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	@Column(name = "confirmation_qty", nullable = false, precision = 16, scale = 3)
	public BigDecimal getConfirmationQty() {
		return this.confirmationQty;
	}

	public void setConfirmationQty(BigDecimal confirmationQty) {
		this.confirmationQty = confirmationQty;
	}

	@Column(name = "reduced_qty", precision = 16, scale = 3)
	public BigDecimal getReducedQty() {
		return this.reducedQty;
	}

	public void setReducedQty(BigDecimal reducedQty) {
		this.reducedQty = reducedQty;
	}

	@Column(name = "is_closed")
	public Boolean getIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(Boolean isClosed) {
		this.isClosed = isClosed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "closed_date", length = 23)
	public Date getClosedDate() {
		return this.closedDate;
	}

	public void setClosedDate(Date closedDate) {
		this.closedDate = closedDate;
	}

	@Column(name = "closed_by", length = 50)
	public String getClosedBy() {
		return this.closedBy;
	}

	public void setClosedBy(String closedBy) {
		this.closedBy = closedBy;
	}

	@Column(name = "change_remark", length = 250)
	public String getChangeRemark() {
		return this.changeRemark;
	}

	public void setChangeRemark(String changeRemark) {
		this.changeRemark = changeRemark;
	}

	@Column(name = "is_deleted", nullable = false)
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poItemsConfirmation")
	public Set<PoItemsConfirmationDnBatch> getPoItemsConfirmationDnBatches() {
		return this.poItemsConfirmationDnBatches;
	}

	public void setPoItemsConfirmationDnBatches(Set<PoItemsConfirmationDnBatch> poItemsConfirmationDnBatches) {
		this.poItemsConfirmationDnBatches = poItemsConfirmationDnBatches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poItemsConfirmation")
	public Set<PoItemsIssues> getPoItemsIssueses() {
		return this.poItemsIssueses;
	}

	public void setPoItemsIssueses(Set<PoItemsIssues> poItemsIssueses) {
		this.poItemsIssueses = poItemsIssueses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poItemsConfirmation")
	public Set<PoItemInspection> getPoItemInspections() {
		return this.poItemInspections;
	}

	public void setPoItemInspections(Set<PoItemInspection> poItemInspections) {
		this.poItemInspections = poItemInspections;
	}

}
