package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;

/**
 * PoItemsIssuesAction generated by hbm2java
 */
@Entity
@Table(name = "po_items_issues_action", schema = "bpi" )
public class PoItemsIssuesAction implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private MsIssueAction msIssueAction;
	private PoItemsIssues poItemsIssues;
	private String remark;
	private String actionBy;
	private Date actionDate;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private String emails;
	private String sendTo;
	private Integer roleId;
	private Integer round;

	public PoItemsIssuesAction() {
	}

	public PoItemsIssuesAction(Integer id, String createdBy, Date createdDate) {
		this.id = id;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public PoItemsIssuesAction(Integer id, MsIssueAction msIssueAction, PoItemsIssues poItemsIssues, String remark,
			String actionBy, Date actionDate, Boolean isDeleted, String createdBy, Date createdDate, String updatedBy,
			Date updatedDate, String emails, String sendTo, Integer roleId, Integer round) {
		this.id = id;
		this.msIssueAction = msIssueAction;
		this.poItemsIssues = poItemsIssues;
		this.remark = remark;
		this.actionBy = actionBy;
		this.actionDate = actionDate;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.emails = emails;
		this.sendTo = sendTo;
		this.roleId = roleId;
		this.round = round;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ms_action_id")
	public MsIssueAction getMsIssueAction() {
		return this.msIssueAction;
	}

	public void setMsIssueAction(MsIssueAction msIssueAction) {
		this.msIssueAction = msIssueAction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_issues_id")
	public PoItemsIssues getPoItemsIssues() {
		return this.poItemsIssues;
	}

	public void setPoItemsIssues(PoItemsIssues poItemsIssues) {
		this.poItemsIssues = poItemsIssues;
	}

	@Column(name = "Remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "action_by", length = 50)
	public String getActionBy() {
		return this.actionBy;
	}

	public void setActionBy(String actionBy) {
		this.actionBy = actionBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "action_date", length = 23)
	public Date getActionDate() {
		return this.actionDate;
	}

	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "emails")
	public String getEmails() {
		return this.emails;
	}

	public void setEmails(String emails) {
		this.emails = emails;
	}

	@Column(name = "send_to", length = 150)
	public String getSendTo() {
		return this.sendTo;
	}

	public void setSendTo(String sendTo) {
		this.sendTo = sendTo;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "round")
	public Integer getRound() {
		return this.round;
	}

	public void setRound(Integer round) {
		this.round = round;
	}

}
