package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;

/**
 * PoItemsScheduleDnBatch generated by hbm2java
 */
@Entity
@Table(name = "po_items_schedule_dn_batch", schema = "bpi" )
public class PoItemsScheduleDnBatch implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private PoItemsBatch poItemsBatch;
	private PoItemsSchedule poItemsSchedule;
	private String deliveryNote;
	private Integer lineItem;
	private String vendorBatch;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public PoItemsScheduleDnBatch() {
	}

	public PoItemsScheduleDnBatch(Integer id, PoItemsBatch poItemsBatch, PoItemsSchedule poItemsSchedule,
			String deliveryNote, Integer lineItem, Boolean isDeleted, String createdBy, Date createdDate) {
		this.id = id;
		this.poItemsBatch = poItemsBatch;
		this.poItemsSchedule = poItemsSchedule;
		this.deliveryNote = deliveryNote;
		this.lineItem = lineItem;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public PoItemsScheduleDnBatch(Integer id, PoItemsBatch poItemsBatch, PoItemsSchedule poItemsSchedule,
			String deliveryNote, Integer lineItem, String vendorBatch, Boolean isDeleted, String createdBy,
			Date createdDate, String updatedBy, Date updatedDate) {
		this.id = id;
		this.poItemsBatch = poItemsBatch;
		this.poItemsSchedule = poItemsSchedule;
		this.deliveryNote = deliveryNote;
		this.lineItem = lineItem;
		this.vendorBatch = vendorBatch;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "items_batch_id", nullable = false)
	public PoItemsBatch getPoItemsBatch() {
		return this.poItemsBatch;
	}

	public void setPoItemsBatch(PoItemsBatch poItemsBatch) {
		this.poItemsBatch = poItemsBatch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_schedule_id", nullable = false)
	public PoItemsSchedule getPoItemsSchedule() {
		return this.poItemsSchedule;
	}

	public void setPoItemsSchedule(PoItemsSchedule poItemsSchedule) {
		this.poItemsSchedule = poItemsSchedule;
	}

	@Column(name = "delivery_note", nullable = false)
	public String getDeliveryNote() {
		return this.deliveryNote;
	}

	public void setDeliveryNote(String deliveryNote) {
		this.deliveryNote = deliveryNote;
	}

	@Column(name = "line_item", nullable = false)
	public Integer getLineItem() {
		return this.lineItem;
	}

	public void setLineItem(Integer lineItem) {
		this.lineItem = lineItem;
	}

	@Column(name = "vendor_batch", length = 35)
	public String getVendorBatch() {
		return this.vendorBatch;
	}

	public void setVendorBatch(String vendorBatch) {
		this.vendorBatch = vendorBatch;
	}

	@Column(name = "is_deleted", nullable = false)
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
