package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PoItemsIssues generated by hbm2java
 */
@Entity
@Table(name = "po_items_issues", schema = "bpi" )
public class PoItemsIssues implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private Material material;
	private MaterialGroup materialGroup;
	private MsIssueOption msIssueOption;
	private MsIssueStage msIssueStage;
	private MsIssueStatus msIssueStatus;
	private MsReceiveType msReceiveType;
	private Po po;
	private PoItems poItems;
	private PoItemsConfirmation poItemsConfirmation;
	private PoItemsSchedule poItemsSchedule;
	private String code;
	private BigDecimal issuePackageNum;
	private Boolean isQaConsult;
	private String batchNo;
	private String nextAction;
	private String remark;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Integer round;
	private Integer inspectionId;
	private Integer sbReceiveId;
	private Set<PoItemsIssuesFiles> poItemsIssuesFileses = new HashSet<PoItemsIssuesFiles>(0);
	private Set<PoItemsIssuesAction> poItemsIssuesActions = new HashSet<PoItemsIssuesAction>(0);

	public PoItemsIssues() {
	}

	public PoItemsIssues(Integer id, Material material, MaterialGroup materialGroup, MsIssueStage msIssueStage, Po po
			) {
		this.id = id;
		this.material = material;
		this.materialGroup = materialGroup;
		this.msIssueStage = msIssueStage;
		this.po = po;
	}

	public PoItemsIssues(Integer id, Material material, MaterialGroup materialGroup, MsIssueOption msIssueOption,
			MsIssueStage msIssueStage, MsIssueStatus msIssueStatus, MsReceiveType msReceiveType, Po po, PoItems poItems,
			PoItemsConfirmation poItemsConfirmation, PoItemsSchedule poItemsSchedule, String code,
			BigDecimal issuePackageNum, Boolean isQaConsult, String batchNo, String nextAction, String remark,
			Boolean isDeleted, String createdBy, Date createdDate, String updatedBy, Date updatedDate, Integer round,
			Integer inspectionId, Integer sbReceiveId, Set<PoItemsIssuesFiles> poItemsIssuesFileses,
			Set<PoItemsIssuesAction> poItemsIssuesActions) {
		this.id = id;
		this.material = material;
		this.materialGroup = materialGroup;
		this.msIssueOption = msIssueOption;
		this.msIssueStage = msIssueStage;
		this.msIssueStatus = msIssueStatus;
		this.msReceiveType = msReceiveType;
		this.po = po;
		this.poItems = poItems;
		this.poItemsConfirmation = poItemsConfirmation;
		this.poItemsSchedule = poItemsSchedule;
		this.code = code;
		this.issuePackageNum = issuePackageNum;
		this.isQaConsult = isQaConsult;
		this.batchNo = batchNo;
		this.nextAction = nextAction;
		this.remark = remark;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.round = round;
		this.inspectionId = inspectionId;
		this.sbReceiveId = sbReceiveId;
		this.poItemsIssuesFileses = poItemsIssuesFileses;
		this.poItemsIssuesActions = poItemsIssuesActions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "material_id", nullable = false)
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mat_group_id", nullable = false)
	public MaterialGroup getMaterialGroup() {
		return this.materialGroup;
	}

	public void setMaterialGroup(MaterialGroup materialGroup) {
		this.materialGroup = materialGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "option_id")
	public MsIssueOption getMsIssueOption() {
		return this.msIssueOption;
	}

	public void setMsIssueOption(MsIssueOption msIssueOption) {
		this.msIssueOption = msIssueOption;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "issue_state_id", nullable = false)
	public MsIssueStage getMsIssueStage() {
		return this.msIssueStage;
	}

	public void setMsIssueStage(MsIssueStage msIssueStage) {
		this.msIssueStage = msIssueStage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status_id")
	public MsIssueStatus getMsIssueStatus() {
		return this.msIssueStatus;
	}

	public void setMsIssueStatus(MsIssueStatus msIssueStatus) {
		this.msIssueStatus = msIssueStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ms_receive_type_id")
	public MsReceiveType getMsReceiveType() {
		return this.msReceiveType;
	}

	public void setMsReceiveType(MsReceiveType msReceiveType) {
		this.msReceiveType = msReceiveType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_id", nullable = false)
	public Po getPo() {
		return this.po;
	}

	public void setPo(Po po) {
		this.po = po;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_id")
	public PoItems getPoItems() {
		return this.poItems;
	}

	public void setPoItems(PoItems poItems) {
		this.poItems = poItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_confirmation_id")
	public PoItemsConfirmation getPoItemsConfirmation() {
		return this.poItemsConfirmation;
	}

	public void setPoItemsConfirmation(PoItemsConfirmation poItemsConfirmation) {
		this.poItemsConfirmation = poItemsConfirmation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_schedule_id")
	public PoItemsSchedule getPoItemsSchedule() {
		return this.poItemsSchedule;
	}

	public void setPoItemsSchedule(PoItemsSchedule poItemsSchedule) {
		this.poItemsSchedule = poItemsSchedule;
	}

	@Column(name = "code", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "issue_package_num", precision = 16, scale = 3)
	public BigDecimal getIssuePackageNum() {
		return this.issuePackageNum;
	}

	public void setIssuePackageNum(BigDecimal issuePackageNum) {
		this.issuePackageNum = issuePackageNum;
	}

	@Column(name = "is_qa_consult")
	public Boolean getIsQaConsult() {
		return this.isQaConsult;
	}

	public void setIsQaConsult(Boolean isQaConsult) {
		this.isQaConsult = isQaConsult;
	}

	@Column(name = "batch_no", length = 50)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Column(name = "next_action", length = 500)
	public String getNextAction() {
		return this.nextAction;
	}

	public void setNextAction(String nextAction) {
		this.nextAction = nextAction;
	}

	@Column(name = "remark", length = 1250)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "round")
	public Integer getRound() {
		return this.round;
	}

	public void setRound(Integer round) {
		this.round = round;
	}

	@Column(name = "inspection_id")
	public Integer getInspectionId() {
		return this.inspectionId;
	}

	public void setInspectionId(Integer inspectionId) {
		this.inspectionId = inspectionId;
	}

	@Column(name = "sb_receive_id")
	public Integer getSbReceiveId() {
		return this.sbReceiveId;
	}

	public void setSbReceiveId(Integer sbReceiveId) {
		this.sbReceiveId = sbReceiveId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poItemsIssues")
	public Set<PoItemsIssuesFiles> getPoItemsIssuesFileses() {
		return this.poItemsIssuesFileses;
	}

	public void setPoItemsIssuesFileses(Set<PoItemsIssuesFiles> poItemsIssuesFileses) {
		this.poItemsIssuesFileses = poItemsIssuesFileses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poItemsIssues")
	public Set<PoItemsIssuesAction> getPoItemsIssuesActions() {
		return this.poItemsIssuesActions;
	}

	public void setPoItemsIssuesActions(Set<PoItemsIssuesAction> poItemsIssuesActions) {
		this.poItemsIssuesActions = poItemsIssuesActions;
	}

}
