package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PoItemsQiRelease generated by hbm2java
 */
@Entity
@Table(name = "po_items_qi_release", schema = "bpi" )
public class PoItemsQiRelease implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private MsPlant msPlant;
	private MsStorageLocation msStorageLocation;
	private PoItems poItems;
	private PoItemsQi poItemsQi;
	private BigDecimal releaseQuantity;
	private String releaseBatch;
	private Integer stockTypeId;
	private Date releaseDate;
	private String releaseFile;
	private Integer releaseStatus;
	private String remark;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private String companyCode;
	private Set<PoItemsQiReleaseMessage> poItemsQiReleaseMessages = new HashSet<PoItemsQiReleaseMessage>(0);

	public PoItemsQiRelease() {
	}

	public PoItemsQiRelease(Integer id, MsPlant msPlant, MsStorageLocation msStorageLocation, PoItems poItems,
			PoItemsQi poItemsQi, BigDecimal releaseQuantity, String releaseBatch, Integer stockTypeId,
			Boolean isDeleted, String createdBy, Date createdDate) {
		this.id = id;
		this.msPlant = msPlant;
		this.msStorageLocation = msStorageLocation;
		this.poItems = poItems;
		this.poItemsQi = poItemsQi;
		this.releaseQuantity = releaseQuantity;
		this.releaseBatch = releaseBatch;
		this.stockTypeId = stockTypeId;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public PoItemsQiRelease(Integer id, MsPlant msPlant, MsStorageLocation msStorageLocation, PoItems poItems,
			PoItemsQi poItemsQi, BigDecimal releaseQuantity, String releaseBatch, Integer stockTypeId, Date releaseDate,
			String releaseFile, Integer releaseStatus, String remark, Boolean isDeleted, String createdBy,
			Date createdDate, String updatedBy, Date updatedDate, String companyCode,
			Set<PoItemsQiReleaseMessage> poItemsQiReleaseMessages) {
		this.id = id;
		this.msPlant = msPlant;
		this.msStorageLocation = msStorageLocation;
		this.poItems = poItems;
		this.poItemsQi = poItemsQi;
		this.releaseQuantity = releaseQuantity;
		this.releaseBatch = releaseBatch;
		this.stockTypeId = stockTypeId;
		this.releaseDate = releaseDate;
		this.releaseFile = releaseFile;
		this.releaseStatus = releaseStatus;
		this.remark = remark;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.companyCode = companyCode;
		this.poItemsQiReleaseMessages = poItemsQiReleaseMessages;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plant_id", nullable = false)
	public MsPlant getMsPlant() {
		return this.msPlant;
	}

	public void setMsPlant(MsPlant msPlant) {
		this.msPlant = msPlant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "storage_location_id", nullable = false)
	public MsStorageLocation getMsStorageLocation() {
		return this.msStorageLocation;
	}

	public void setMsStorageLocation(MsStorageLocation msStorageLocation) {
		this.msStorageLocation = msStorageLocation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_item_id", nullable = false)
	public PoItems getPoItems() {
		return this.poItems;
	}

	public void setPoItems(PoItems poItems) {
		this.poItems = poItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_items_qi", nullable = false)
	public PoItemsQi getPoItemsQi() {
		return this.poItemsQi;
	}

	public void setPoItemsQi(PoItemsQi poItemsQi) {
		this.poItemsQi = poItemsQi;
	}

	@Column(name = "release_quantity", nullable = false, precision = 16, scale = 3)
	public BigDecimal getReleaseQuantity() {
		return this.releaseQuantity;
	}

	public void setReleaseQuantity(BigDecimal releaseQuantity) {
		this.releaseQuantity = releaseQuantity;
	}

	@Column(name = "release_batch", nullable = false, length = 10)
	public String getReleaseBatch() {
		return this.releaseBatch;
	}

	public void setReleaseBatch(String releaseBatch) {
		this.releaseBatch = releaseBatch;
	}

	@Column(name = "stock_type_id", nullable = false)
	public Integer getStockTypeId() {
		return this.stockTypeId;
	}

	public void setStockTypeId(Integer stockTypeId) {
		this.stockTypeId = stockTypeId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "release_date", length = 10)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "release_file", length = 30)
	public String getReleaseFile() {
		return this.releaseFile;
	}

	public void setReleaseFile(String releaseFile) {
		this.releaseFile = releaseFile;
	}

	@Column(name = "release_status")
	public Integer getReleaseStatus() {
		return this.releaseStatus;
	}

	public void setReleaseStatus(Integer releaseStatus) {
		this.releaseStatus = releaseStatus;
	}

	@Column(name = "remark", length = 550)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "is_deleted", nullable = false)
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", nullable = false, length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "company_code")
	public String getCompanyCode() {
		return this.companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poItemsQiRelease")
	public Set<PoItemsQiReleaseMessage> getPoItemsQiReleaseMessages() {
		return this.poItemsQiReleaseMessages;
	}

	public void setPoItemsQiReleaseMessages(Set<PoItemsQiReleaseMessage> poItemsQiReleaseMessages) {
		this.poItemsQiReleaseMessages = poItemsQiReleaseMessages;
	}

}
