package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;

/**
 * PoMatchItemsFiles generated by hbm2java
 */
@Entity
@Table(name = "po_match_items_files", schema = "bpi" )
public class PoMatchItemsFiles implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private PoMatchItems poMatchItems;
	private Integer fileType;
	private String linkFile;
	private String fileName;
	private String contentType;
	private Long size;
	private byte[] content;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;

	public PoMatchItemsFiles() {
	}

	public PoMatchItemsFiles(Integer id, String fileName, String contentType) {
		this.id = id;
		this.fileName = fileName;
		this.contentType = contentType;
	}

	public PoMatchItemsFiles(Integer id, PoMatchItems poMatchItems, Integer fileType, String linkFile, String fileName,
			String contentType, Long size, byte[] content, Boolean isDeleted, String createdBy, Date createdDate,
			String updatedBy, Date updatedDate) {
		this.id = id;
		this.poMatchItems = poMatchItems;
		this.fileType = fileType;
		this.linkFile = linkFile;
		this.fileName = fileName;
		this.contentType = contentType;
		this.size = size;
		this.content = content;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "po_match_items_id")
	public PoMatchItems getPoMatchItems() {
		return this.poMatchItems;
	}

	public void setPoMatchItems(PoMatchItems poMatchItems) {
		this.poMatchItems = poMatchItems;
	}

	@Column(name = "file_type")
	public Integer getFileType() {
		return this.fileType;
	}

	public void setFileType(Integer fileType) {
		this.fileType = fileType;
	}

	@Column(name = "link_file", length = 550)
	public String getLinkFile() {
		return this.linkFile;
	}

	public void setLinkFile(String linkFile) {
		this.linkFile = linkFile;
	}

	@Column(name = "file_name", nullable = false)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "content_type", nullable = false)
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "size", precision = 18, scale = 0)
	public Long getSize() {
		return this.size;
	}

	public void setSize(Long size) {
		this.size = size;
	}

	@Column(name = "content")
	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
