package com.siampharm.sampling.model;
// Generated Feb 25, 2019 2:45:54 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PoMatchItems generated by hbm2java
 */
@Entity
@Table(name = "po_match_items", schema = "bpi" )
public class PoMatchItems implements java.io.Serializable {
	private static final long serialVersionUID = 2620159661845577905L;
	private Integer id;
	private Po poBySpPoId;
	private Po poBySbPoId;
	private PoItems poItemsBySbPoItemId;
	private PoItems poItemsBySpPoItemId;
	private PoItemsSchedule poItemsScheduleBySpPoItemScheduleId;
	private PoItemsSchedule poItemsScheduleBySbPoItemScheduleId;
	private Integer spLineItem;
	private Integer sbLineItem;
	private Boolean isDeleted;
	private String createdBy;
	private Date createdDate;
	private String updatedBy;
	private Date updatedDate;
	private Set<PoMatchItemsFiles> poMatchItemsFileses = new HashSet<PoMatchItemsFiles>(0);

	public PoMatchItems() {
	}

	public PoMatchItems(Integer id, Po poBySpPoId, Po poBySbPoId) {
		this.id = id;
		this.poBySpPoId = poBySpPoId;
		this.poBySbPoId = poBySbPoId;
	}

	public PoMatchItems(Integer id, Po poBySpPoId, Po poBySbPoId, PoItems poItemsBySbPoItemId,
			PoItems poItemsBySpPoItemId, PoItemsSchedule poItemsScheduleBySpPoItemScheduleId,
			PoItemsSchedule poItemsScheduleBySbPoItemScheduleId, Integer spLineItem, Integer sbLineItem,
			Boolean isDeleted, String createdBy, Date createdDate, String updatedBy, Date updatedDate,
			Set<PoMatchItemsFiles> poMatchItemsFileses) {
		this.id = id;
		this.poBySpPoId = poBySpPoId;
		this.poBySbPoId = poBySbPoId;
		this.poItemsBySbPoItemId = poItemsBySbPoItemId;
		this.poItemsBySpPoItemId = poItemsBySpPoItemId;
		this.poItemsScheduleBySpPoItemScheduleId = poItemsScheduleBySpPoItemScheduleId;
		this.poItemsScheduleBySbPoItemScheduleId = poItemsScheduleBySbPoItemScheduleId;
		this.spLineItem = spLineItem;
		this.sbLineItem = sbLineItem;
		this.isDeleted = isDeleted;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.poMatchItemsFileses = poMatchItemsFileses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sp_po_id", nullable = false)
	public Po getPoBySpPoId() {
		return this.poBySpPoId;
	}

	public void setPoBySpPoId(Po poBySpPoId) {
		this.poBySpPoId = poBySpPoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sb_po_id", nullable = false)
	public Po getPoBySbPoId() {
		return this.poBySbPoId;
	}

	public void setPoBySbPoId(Po poBySbPoId) {
		this.poBySbPoId = poBySbPoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sb_po_item_id")
	public PoItems getPoItemsBySbPoItemId() {
		return this.poItemsBySbPoItemId;
	}

	public void setPoItemsBySbPoItemId(PoItems poItemsBySbPoItemId) {
		this.poItemsBySbPoItemId = poItemsBySbPoItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sp_po_item_id")
	public PoItems getPoItemsBySpPoItemId() {
		return this.poItemsBySpPoItemId;
	}

	public void setPoItemsBySpPoItemId(PoItems poItemsBySpPoItemId) {
		this.poItemsBySpPoItemId = poItemsBySpPoItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sp_po_item_schedule_id")
	public PoItemsSchedule getPoItemsScheduleBySpPoItemScheduleId() {
		return this.poItemsScheduleBySpPoItemScheduleId;
	}

	public void setPoItemsScheduleBySpPoItemScheduleId(PoItemsSchedule poItemsScheduleBySpPoItemScheduleId) {
		this.poItemsScheduleBySpPoItemScheduleId = poItemsScheduleBySpPoItemScheduleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sb_po_item_schedule_id")
	public PoItemsSchedule getPoItemsScheduleBySbPoItemScheduleId() {
		return this.poItemsScheduleBySbPoItemScheduleId;
	}

	public void setPoItemsScheduleBySbPoItemScheduleId(PoItemsSchedule poItemsScheduleBySbPoItemScheduleId) {
		this.poItemsScheduleBySbPoItemScheduleId = poItemsScheduleBySbPoItemScheduleId;
	}

	@Column(name = "sp_line_item")
	public Integer getSpLineItem() {
		return this.spLineItem;
	}

	public void setSpLineItem(Integer spLineItem) {
		this.spLineItem = spLineItem;
	}

	@Column(name = "sb_line_item")
	public Integer getSbLineItem() {
		return this.sbLineItem;
	}

	public void setSbLineItem(Integer sbLineItem) {
		this.sbLineItem = sbLineItem;
	}

	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 23)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", length = 50)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 23)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poMatchItems")
	public Set<PoMatchItemsFiles> getPoMatchItemsFileses() {
		return this.poMatchItemsFileses;
	}

	public void setPoMatchItemsFileses(Set<PoMatchItemsFiles> poMatchItemsFileses) {
		this.poMatchItemsFileses = poMatchItemsFileses;
	}

}
